name: rideshare-backend

services:
  web-prod:
    build: .
    ports:
      - "8102:8000"
    depends_on:
      - db
      - redis
    profiles:
      - prod

  web-dev:
    build: .
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./app/src
        - action: rebuild
          path: deno.json
        - action: rebuild
          path: deno.lock
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    profiles:
      - dev

  web-staging:
    build: .
    command: ["deno", "run", "prod"]
    env_file:
      - .env.staging
    ports:
      - "8100:8000"
    depends_on:
      - db-staging
      - redis-staging
    profiles:
      - staging
  
  db-staging:
    image: postgres:17.5-bookworm
    env_file:
      - .env.staging
    user: 1001:1001
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - staging

  db:
    image: postgres:17.5-bookworm
    container_name: db
    env_file:
      - .env
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - dev
      - prod

  redis:
    image: redis:8.2.1
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 3
    env_file: .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    profiles:
      - dev
      - prod

  redis-staging:
    image: redis:8.2.1
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 3
    env_file: .env.staging
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    profiles:
      - staging
