CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phone_number" varchar,
  "email" varchar,
  "name" varchar
);

CREATE TABLE "rides" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_by" int,
  "comments" varchar,
  "departure_start_time" timestamp,
  "departure_end_time" timestamp,
  "max_member_count" int
);

CREATE TABLE "ride_members" (
  "user_id" int,
  "ride_id" int,
  PRIMARY KEY ("user_id", "ride_id")
);

CREATE TABLE "user_requests" (
  "user_id" int,
  "ride_id" int,
  PRIMARY KEY ("user_id", "ride_id")
);

CREATE TABLE "user_bookmarks" (
  "user_id" int,
  "ride_id" int,
  PRIMARY KEY ("user_id", "ride_id")
);

CREATE TABLE "stops" (
  "ride_id" int,
  "location" varchar,
  "order" int,
  PRIMARY KEY ("ride_id", "order")
);

ALTER TABLE "rides" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "ride_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "ride_members" ADD FOREIGN KEY ("ride_id") REFERENCES "rides" ("id");

ALTER TABLE "user_requests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_requests" ADD FOREIGN KEY ("ride_id") REFERENCES "rides" ("id");

ALTER TABLE "user_bookmarks" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_bookmarks" ADD FOREIGN KEY ("ride_id") REFERENCES "rides" ("id");

ALTER TABLE "stops" ADD FOREIGN KEY ("ride_id") REFERENCES "rides" ("id");
